/** Nigerian states + FCT, used by location pickers across the app. */
export const NIGERIAN_STATES = [
  'Abia', 'Abuja (FCT)', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo',
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa',
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
]

/** Nigerian banks, fintechs, PSBs + microfinance banks for the vendor payout
 * dropdown. Phase 1 collects the account without verifying it, so this is a
 * plain reference list (alphabetical). The bank picker also allows a typed-in
 * value, so anything missing here can still be entered by the vendor. */
export const NIGERIAN_BANKS = [
  '9 Payment Service Bank (9PSB)',
  'AB Microfinance Bank',
  'Access Bank',
  'Accion Microfinance Bank',
  'Addosser Microfinance Bank',
  'Advans La Fayette Microfinance Bank',
  'ALAT by Wema',
  'Amju Unique Microfinance Bank',
  'Baobab Microfinance Bank',
  'Bowen Microfinance Bank',
  'Carbon',
  'CEMCS Microfinance Bank',
  'Citibank Nigeria',
  'Coronation Merchant Bank',
  'Covenant Microfinance Bank',
  'Ecobank Nigeria',
  'Ekondo Microfinance Bank',
  'Eyowo',
  'FairMoney Microfinance Bank',
  'FBNQuest Merchant Bank',
  'Fidelity Bank',
  'Fina Trust Microfinance Bank',
  'Firmus Microfinance Bank',
  'First Bank of Nigeria',
  'First City Monument Bank (FCMB)',
  'Fortis Microfinance Bank',
  'FSDH Merchant Bank',
  'Fundall',
  'Globus Bank',
  'GoMoney',
  'Greenwich Merchant Bank',
  'Guaranty Trust Bank (GTBank)',
  'Hackman Microfinance Bank',
  'Hope Payment Service Bank',
  'Ibile Microfinance Bank',
  'Infinity Microfinance Bank',
  'Jaiz Bank',
  'Keystone Bank',
  'Kuda Bank',
  'LAPO Microfinance Bank',
  'Links Microfinance Bank',
  'Lotus Bank',
  'Mayfair Microfinance Bank',
  'Mint Microfinance Bank (Mintyn)',
  'MoMo Payment Service Bank',
  'Money Master Payment Service Bank',
  'Moniepoint MFB',
  'Mutual Trust Microfinance Bank',
  'Nirsal Microfinance Bank',
  'Nova Bank',
  'NPF Microfinance Bank',
  'OPay',
  'Optimus Bank',
  'Paga',
  'Page Financials',
  'PalmPay',
  'Parallex Bank',
  'Parkway (ReadyCash)',
  'Peace Microfinance Bank',
  'Personal Trust Microfinance Bank',
  'Petra Microfinance Bank',
  'Polaris Bank',
  'PremiumTrust Bank',
  'Providus Bank',
  'Rand Merchant Bank',
  'Regent Microfinance Bank',
  'Renmoney Microfinance Bank',
  'Rephidim Microfinance Bank',
  'Rubies Microfinance Bank',
  'Safe Haven Microfinance Bank',
  'Seed Capital Microfinance Bank',
  'Signature Bank',
  'Smartcash Payment Service Bank',
  'Sparkle Microfinance Bank',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Stanford Microfinance Bank',
  'Stellas Microfinance Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'TAJBank',
  'TCF Microfinance Bank',
  'Titan Trust Bank',
  'Trust Microfinance Bank',
  'Uniben Microfinance Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Unity Bank',
  'VFD Microfinance Bank',
  'Wema Bank',
  'Zenith Bank',
]
