/** Nigerian states + FCT, used by location pickers across the app. */
export const NIGERIAN_STATES = [
  'Abia', 'Abuja (FCT)', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo',
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa',
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
]

/** Nigerian banks, fintechs, PSBs + popular microfinance banks for the vendor
 * payout dropdown. Phase 1 collects the account without verifying it, so this is
 * a plain reference list (alphabetical). Not exhaustive — add on request. */
export const NIGERIAN_BANKS = [
  '9 Payment Service Bank (9PSB)',
  'AB Microfinance Bank',
  'Access Bank',
  'Accion Microfinance Bank',
  'ALAT by Wema',
  'Baobab Microfinance Bank',
  'Carbon',
  'Citibank Nigeria',
  'Covenant Microfinance Bank',
  'Ecobank Nigeria',
  'Eyowo',
  'FairMoney Microfinance Bank',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank (FCMB)',
  'Globus Bank',
  'Guaranty Trust Bank (GTBank)',
  'Hope Payment Service Bank',
  'Ibile Microfinance Bank',
  'Jaiz Bank',
  'Keystone Bank',
  'Kuda Bank',
  'LAPO Microfinance Bank',
  'Lotus Bank',
  'Mint Microfinance Bank (Mintyn)',
  'MoMo Payment Service Bank',
  'Money Master Payment Service Bank',
  'Moniepoint MFB',
  'Mutual Trust Microfinance Bank',
  'NPF Microfinance Bank',
  'OPay',
  'Optimus Bank',
  'Paga',
  'Page Financials',
  'PalmPay',
  'Parallex Bank',
  'Polaris Bank',
  'PremiumTrust Bank',
  'Providus Bank',
  'Rubies Microfinance Bank',
  'Smartcash Payment Service Bank',
  'Sparkle Microfinance Bank',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'TAJBank',
  'Titan Trust Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Unity Bank',
  'VFD Microfinance Bank',
  'Wema Bank',
  'Zenith Bank',
]
